/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HeadingBlock {
    content: Array<RichTextSpan>;
    level: HeadingLevel;
}
export interface WritingPageContent {
    title: string;
    subtitle: string;
}
export interface ImageBlock {
    alt: string;
    url: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Tag = string;
export interface PageContent {
    title: string;
    content: Array<RichText>;
    links: Array<[string, string]>;
    subtitle: string;
}
export interface RichTextBlock {
    content: Array<RichTextSpan>;
}
export interface RichTextListItem {
    content: Array<RichTextSpan>;
}
export interface Essay {
    id: bigint;
    title: string;
    isPublished: boolean;
    publishDate: Time;
    body: Array<RichText>;
    tags: Array<Tag>;
    heroImage?: ExternalBlob;
    subtitle: string;
}
export type PageId = string;
export interface RichTextSpan {
    link?: string;
    text: string;
    isBold: boolean;
    isItalic: boolean;
}
export type RichText = {
    __kind__: "orderedList";
    orderedList: Array<RichTextListItem>;
} | {
    __kind__: "code";
    code: RichTextBlock;
} | {
    __kind__: "unorderedList";
    unorderedList: Array<RichTextListItem>;
} | {
    __kind__: "list";
    list: Array<RichTextListItem>;
} | {
    __kind__: "quote";
    quote: RichTextBlock;
} | {
    __kind__: "heading";
    heading: HeadingBlock;
} | {
    __kind__: "image";
    image: ImageBlock;
} | {
    __kind__: "paragraph";
    paragraph: RichTextBlock;
};
export interface UserProfile {
    name: string;
}
export enum HeadingLevel {
    h1 = "h1",
    h2 = "h2"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEssay(title: string, subtitle: string, body: Array<RichText>, heroImage: ExternalBlob | null, tagsInput: Array<Tag>, publishDate: Time, isPublished: boolean): Promise<bigint>;
    deleteEssay(id: bigint): Promise<void>;
    filterPublishedEssaysByTag(tag: Tag): Promise<Array<Essay>>;
    getAllEssaysForAdmin(): Promise<Array<Essay>>;
    getAllTags(): Promise<Array<Tag>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEssayForAdmin(id: bigint): Promise<Essay>;
    getPageContent(pageId: PageId): Promise<PageContent>;
    getPublishedEssay(id: bigint): Promise<Essay>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWritingPageContent(): Promise<WritingPageContent>;
    initializeAccessControl(): Promise<void>;
    initializeDefaultPages(): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listPublishedEssays(): Promise<Array<Essay>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEssay(id: bigint, title: string, subtitle: string, body: Array<RichText>, heroImage: ExternalBlob | null, tagsInput: Array<Tag>, publishDate: Time, isPublished: boolean): Promise<void>;
    updatePageContent(pageId: PageId, content: PageContent): Promise<void>;
    updateWritingPageContent(content: WritingPageContent): Promise<void>;
    uploadImage(image: ExternalBlob): Promise<ExternalBlob>;
}
import type { Essay as _Essay, ExternalBlob as _ExternalBlob, HeadingBlock as _HeadingBlock, HeadingLevel as _HeadingLevel, ImageBlock as _ImageBlock, PageContent as _PageContent, RichText as _RichText, RichTextBlock as _RichTextBlock, RichTextListItem as _RichTextListItem, RichTextSpan as _RichTextSpan, Tag as _Tag, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEssay(arg0: string, arg1: string, arg2: Array<RichText>, arg3: ExternalBlob | null, arg4: Array<Tag>, arg5: Time, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEssay(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEssay(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async deleteEssay(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEssay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEssay(arg0);
            return result;
        }
    }
    async filterPublishedEssaysByTag(arg0: Tag): Promise<Array<Essay>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPublishedEssaysByTag(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPublishedEssaysByTag(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEssaysForAdmin(): Promise<Array<Essay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEssaysForAdmin();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEssaysForAdmin();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTags(): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEssayForAdmin(arg0: bigint): Promise<Essay> {
        if (this.processError) {
            try {
                const result = await this.actor.getEssayForAdmin(arg0);
                return from_candid_Essay_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEssayForAdmin(arg0);
            return from_candid_Essay_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPageContent(arg0: PageId): Promise<PageContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageContent(arg0);
                return from_candid_PageContent_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageContent(arg0);
            return from_candid_PageContent_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedEssay(arg0: bigint): Promise<Essay> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedEssay(arg0);
                return from_candid_Essay_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedEssay(arg0);
            return from_candid_Essay_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWritingPageContent(): Promise<WritingPageContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getWritingPageContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWritingPageContent();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeDefaultPages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultPages();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPublishedEssays(): Promise<Array<Essay>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedEssays();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedEssays();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEssay(arg0: bigint, arg1: string, arg2: string, arg3: Array<RichText>, arg4: ExternalBlob | null, arg5: Array<Tag>, arg6: Time, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEssay(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEssay(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return result;
        }
    }
    async updatePageContent(arg0: PageId, arg1: PageContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePageContent(arg0, to_candid_PageContent_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePageContent(arg0, to_candid_PageContent_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWritingPageContent(arg0: WritingPageContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWritingPageContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWritingPageContent(arg0);
            return result;
        }
    }
    async uploadImage(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Essay_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Essay): Promise<Essay> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HeadingBlock_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeadingBlock): HeadingBlock {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_HeadingLevel_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeadingLevel): HeadingLevel {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PageContent_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageContent): PageContent {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_RichTextBlock_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RichTextBlock): RichTextBlock {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RichTextListItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RichTextListItem): RichTextListItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RichTextSpan_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RichTextSpan): RichTextSpan {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RichText_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RichText): RichText {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    publishDate: _Time;
    body: Array<_RichText>;
    tags: Array<_Tag>;
    heroImage: [] | [_ExternalBlob];
    subtitle: string;
}): Promise<{
    id: bigint;
    title: string;
    isPublished: boolean;
    publishDate: Time;
    body: Array<RichText>;
    tags: Array<Tag>;
    heroImage?: ExternalBlob;
    subtitle: string;
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        publishDate: value.publishDate,
        body: from_candid_vec_n29(_uploadFile, _downloadFile, value.body),
        tags: value.tags,
        heroImage: record_opt_to_undefined(await from_candid_opt_n44(_uploadFile, _downloadFile, value.heroImage)),
        subtitle: value.subtitle
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: Array<_RichTextSpan>;
}): {
    content: Array<RichTextSpan>;
} {
    return {
        content: from_candid_vec_n35(_uploadFile, _downloadFile, value.content)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    link: [] | [string];
    text: string;
    isBold: boolean;
    isItalic: boolean;
}): {
    link?: string;
    text: string;
    isBold: boolean;
    isItalic: boolean;
} {
    return {
        link: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.link)),
        text: value.text,
        isBold: value.isBold,
        isItalic: value.isItalic
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: Array<_RichTextSpan>;
    level: _HeadingLevel;
}): {
    content: Array<RichTextSpan>;
    level: HeadingLevel;
} {
    return {
        content: from_candid_vec_n35(_uploadFile, _downloadFile, value.content),
        level: from_candid_HeadingLevel_n42(_uploadFile, _downloadFile, value.level)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: Array<_RichText>;
    links: Array<[string, string]>;
    subtitle: string;
}): {
    title: string;
    content: Array<RichText>;
    links: Array<[string, string]>;
    subtitle: string;
} {
    return {
        title: value.title,
        content: from_candid_vec_n29(_uploadFile, _downloadFile, value.content),
        links: value.links,
        subtitle: value.subtitle
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderedList: Array<_RichTextListItem>;
} | {
    code: _RichTextBlock;
} | {
    unorderedList: Array<_RichTextListItem>;
} | {
    list: Array<_RichTextListItem>;
} | {
    quote: _RichTextBlock;
} | {
    heading: _HeadingBlock;
} | {
    image: _ImageBlock;
} | {
    paragraph: _RichTextBlock;
}): {
    __kind__: "orderedList";
    orderedList: Array<RichTextListItem>;
} | {
    __kind__: "code";
    code: RichTextBlock;
} | {
    __kind__: "unorderedList";
    unorderedList: Array<RichTextListItem>;
} | {
    __kind__: "list";
    list: Array<RichTextListItem>;
} | {
    __kind__: "quote";
    quote: RichTextBlock;
} | {
    __kind__: "heading";
    heading: HeadingBlock;
} | {
    __kind__: "image";
    image: ImageBlock;
} | {
    __kind__: "paragraph";
    paragraph: RichTextBlock;
} {
    return "orderedList" in value ? {
        __kind__: "orderedList",
        orderedList: from_candid_vec_n32(_uploadFile, _downloadFile, value.orderedList)
    } : "code" in value ? {
        __kind__: "code",
        code: from_candid_RichTextBlock_n39(_uploadFile, _downloadFile, value.code)
    } : "unorderedList" in value ? {
        __kind__: "unorderedList",
        unorderedList: from_candid_vec_n32(_uploadFile, _downloadFile, value.unorderedList)
    } : "list" in value ? {
        __kind__: "list",
        list: from_candid_vec_n32(_uploadFile, _downloadFile, value.list)
    } : "quote" in value ? {
        __kind__: "quote",
        quote: from_candid_RichTextBlock_n39(_uploadFile, _downloadFile, value.quote)
    } : "heading" in value ? {
        __kind__: "heading",
        heading: from_candid_HeadingBlock_n40(_uploadFile, _downloadFile, value.heading)
    } : "image" in value ? {
        __kind__: "image",
        image: value.image
    } : "paragraph" in value ? {
        __kind__: "paragraph",
        paragraph: from_candid_RichTextBlock_n39(_uploadFile, _downloadFile, value.paragraph)
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    h1: null;
} | {
    h2: null;
}): HeadingLevel {
    return "h1" in value ? HeadingLevel.h1 : "h2" in value ? HeadingLevel.h2 : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Essay>): Promise<Array<Essay>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Essay_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RichText>): Array<RichText> {
    return value.map((x)=>from_candid_RichText_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RichTextListItem>): Array<RichTextListItem> {
    return value.map((x)=>from_candid_RichTextListItem_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RichTextSpan>): Array<RichTextSpan> {
    return value.map((x)=>from_candid_RichTextSpan_n36(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HeadingBlock_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeadingBlock): _HeadingBlock {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_HeadingLevel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeadingLevel): _HeadingLevel {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_PageContent_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageContent): _PageContent {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_RichTextBlock_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RichTextBlock): _RichTextBlock {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_RichTextListItem_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RichTextListItem): _RichTextListItem {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_RichTextSpan_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RichTextSpan): _RichTextSpan {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_RichText_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RichText): _RichText {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: Array<RichTextSpan>;
}): {
    content: Array<_RichTextSpan>;
} {
    return {
        content: to_candid_vec_n15(_uploadFile, _downloadFile, value.content)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    link?: string;
    text: string;
    isBold: boolean;
    isItalic: boolean;
}): {
    link: [] | [string];
    text: string;
    isBold: boolean;
    isItalic: boolean;
} {
    return {
        link: value.link ? candid_some(value.link) : candid_none(),
        text: value.text,
        isBold: value.isBold,
        isItalic: value.isItalic
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: Array<RichTextSpan>;
    level: HeadingLevel;
}): {
    content: Array<_RichTextSpan>;
    level: _HeadingLevel;
} {
    return {
        content: to_candid_vec_n15(_uploadFile, _downloadFile, value.content),
        level: to_candid_HeadingLevel_n20(_uploadFile, _downloadFile, value.level)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: Array<RichText>;
    links: Array<[string, string]>;
    subtitle: string;
}): {
    title: string;
    content: Array<_RichText>;
    links: Array<[string, string]>;
    subtitle: string;
} {
    return {
        title: value.title,
        content: to_candid_vec_n10(_uploadFile, _downloadFile, value.content),
        links: value.links,
        subtitle: value.subtitle
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "orderedList";
    orderedList: Array<RichTextListItem>;
} | {
    __kind__: "code";
    code: RichTextBlock;
} | {
    __kind__: "unorderedList";
    unorderedList: Array<RichTextListItem>;
} | {
    __kind__: "list";
    list: Array<RichTextListItem>;
} | {
    __kind__: "quote";
    quote: RichTextBlock;
} | {
    __kind__: "heading";
    heading: HeadingBlock;
} | {
    __kind__: "image";
    image: ImageBlock;
} | {
    __kind__: "paragraph";
    paragraph: RichTextBlock;
}): {
    orderedList: Array<_RichTextListItem>;
} | {
    code: _RichTextBlock;
} | {
    unorderedList: Array<_RichTextListItem>;
} | {
    list: Array<_RichTextListItem>;
} | {
    quote: _RichTextBlock;
} | {
    heading: _HeadingBlock;
} | {
    image: _ImageBlock;
} | {
    paragraph: _RichTextBlock;
} {
    return value.__kind__ === "orderedList" ? {
        orderedList: to_candid_vec_n22(_uploadFile, _downloadFile, value.orderedList)
    } : value.__kind__ === "code" ? {
        code: to_candid_RichTextBlock_n13(_uploadFile, _downloadFile, value.code)
    } : value.__kind__ === "unorderedList" ? {
        unorderedList: to_candid_vec_n22(_uploadFile, _downloadFile, value.unorderedList)
    } : value.__kind__ === "list" ? {
        list: to_candid_vec_n22(_uploadFile, _downloadFile, value.list)
    } : value.__kind__ === "quote" ? {
        quote: to_candid_RichTextBlock_n13(_uploadFile, _downloadFile, value.quote)
    } : value.__kind__ === "heading" ? {
        heading: to_candid_HeadingBlock_n18(_uploadFile, _downloadFile, value.heading)
    } : value.__kind__ === "image" ? {
        image: value.image
    } : value.__kind__ === "paragraph" ? {
        paragraph: to_candid_RichTextBlock_n13(_uploadFile, _downloadFile, value.paragraph)
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeadingLevel): {
    h1: null;
} | {
    h2: null;
} {
    return value == HeadingLevel.h1 ? {
        h1: null
    } : value == HeadingLevel.h2 ? {
        h2: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RichText>): Array<_RichText> {
    return value.map((x)=>to_candid_RichText_n11(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RichTextSpan>): Array<_RichTextSpan> {
    return value.map((x)=>to_candid_RichTextSpan_n16(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RichTextListItem>): Array<_RichTextListItem> {
    return value.map((x)=>to_candid_RichTextListItem_n23(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
