/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Essay {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'publishDate' : Time,
  'body' : Array<RichText>,
  'tags' : Array<Tag>,
  'heroImage' : [] | [ExternalBlob],
  'subtitle' : string,
}
export type ExternalBlob = Uint8Array;
export interface HeadingBlock {
  'content' : Array<RichTextSpan>,
  'level' : HeadingLevel,
}
export type HeadingLevel = { 'h1' : null } |
  { 'h2' : null };
export interface ImageBlock { 'alt' : string, 'url' : string }
export interface PageContent {
  'title' : string,
  'content' : Array<RichText>,
  'links' : Array<[string, string]>,
  'subtitle' : string,
}
export type PageId = string;
export type RichText = { 'orderedList' : Array<RichTextListItem> } |
  { 'code' : RichTextBlock } |
  { 'unorderedList' : Array<RichTextListItem> } |
  { 'list' : Array<RichTextListItem> } |
  { 'quote' : RichTextBlock } |
  { 'heading' : HeadingBlock } |
  { 'image' : ImageBlock } |
  { 'paragraph' : RichTextBlock };
export interface RichTextBlock { 'content' : Array<RichTextSpan> }
export interface RichTextListItem { 'content' : Array<RichTextSpan> }
export interface RichTextSpan {
  'link' : [] | [string],
  'text' : string,
  'isBold' : boolean,
  'isItalic' : boolean,
}
export type Tag = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WritingPageContent { 'title' : string, 'subtitle' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEssay' : ActorMethod<
    [
      string,
      string,
      Array<RichText>,
      [] | [ExternalBlob],
      Array<Tag>,
      Time,
      boolean,
    ],
    bigint
  >,
  'deleteEssay' : ActorMethod<[bigint], undefined>,
  'filterPublishedEssaysByTag' : ActorMethod<[Tag], Array<Essay>>,
  'getAllEssaysForAdmin' : ActorMethod<[], Array<Essay>>,
  'getAllTags' : ActorMethod<[], Array<Tag>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEssayForAdmin' : ActorMethod<[bigint], Essay>,
  'getPageContent' : ActorMethod<[PageId], PageContent>,
  'getPublishedEssay' : ActorMethod<[bigint], Essay>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWritingPageContent' : ActorMethod<[], WritingPageContent>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeDefaultPages' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPublishedEssays' : ActorMethod<[], Array<Essay>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEssay' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<RichText>,
      [] | [ExternalBlob],
      Array<Tag>,
      Time,
      boolean,
    ],
    undefined
  >,
  'updatePageContent' : ActorMethod<[PageId, PageContent], undefined>,
  'updateWritingPageContent' : ActorMethod<[WritingPageContent], undefined>,
  'uploadImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];