/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RichTextSpan = IDL.Record({
  'link' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'isBold' : IDL.Bool,
  'isItalic' : IDL.Bool,
});
export const RichTextListItem = IDL.Record({
  'content' : IDL.Vec(RichTextSpan),
});
export const RichTextBlock = IDL.Record({ 'content' : IDL.Vec(RichTextSpan) });
export const HeadingLevel = IDL.Variant({ 'h1' : IDL.Null, 'h2' : IDL.Null });
export const HeadingBlock = IDL.Record({
  'content' : IDL.Vec(RichTextSpan),
  'level' : HeadingLevel,
});
export const ImageBlock = IDL.Record({ 'alt' : IDL.Text, 'url' : IDL.Text });
export const RichText = IDL.Variant({
  'orderedList' : IDL.Vec(RichTextListItem),
  'code' : RichTextBlock,
  'unorderedList' : IDL.Vec(RichTextListItem),
  'list' : IDL.Vec(RichTextListItem),
  'quote' : RichTextBlock,
  'heading' : HeadingBlock,
  'image' : ImageBlock,
  'paragraph' : RichTextBlock,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Tag = IDL.Text;
export const Time = IDL.Int;
export const Essay = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishDate' : Time,
  'body' : IDL.Vec(RichText),
  'tags' : IDL.Vec(Tag),
  'heroImage' : IDL.Opt(ExternalBlob),
  'subtitle' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PageId = IDL.Text;
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Vec(RichText),
  'links' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'subtitle' : IDL.Text,
});
export const WritingPageContent = IDL.Record({
  'title' : IDL.Text,
  'subtitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEssay' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(RichText),
        IDL.Opt(ExternalBlob),
        IDL.Vec(Tag),
        Time,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEssay' : IDL.Func([IDL.Nat], [], []),
  'filterPublishedEssaysByTag' : IDL.Func([Tag], [IDL.Vec(Essay)], ['query']),
  'getAllEssaysForAdmin' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEssayForAdmin' : IDL.Func([IDL.Nat], [Essay], ['query']),
  'getPageContent' : IDL.Func([PageId], [PageContent], ['query']),
  'getPublishedEssay' : IDL.Func([IDL.Nat], [Essay], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWritingPageContent' : IDL.Func([], [WritingPageContent], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeDefaultPages' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPublishedEssays' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEssay' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(RichText),
        IDL.Opt(ExternalBlob),
        IDL.Vec(Tag),
        Time,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updatePageContent' : IDL.Func([PageId, PageContent], [], []),
  'updateWritingPageContent' : IDL.Func([WritingPageContent], [], []),
  'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RichTextSpan = IDL.Record({
    'link' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'isBold' : IDL.Bool,
    'isItalic' : IDL.Bool,
  });
  const RichTextListItem = IDL.Record({ 'content' : IDL.Vec(RichTextSpan) });
  const RichTextBlock = IDL.Record({ 'content' : IDL.Vec(RichTextSpan) });
  const HeadingLevel = IDL.Variant({ 'h1' : IDL.Null, 'h2' : IDL.Null });
  const HeadingBlock = IDL.Record({
    'content' : IDL.Vec(RichTextSpan),
    'level' : HeadingLevel,
  });
  const ImageBlock = IDL.Record({ 'alt' : IDL.Text, 'url' : IDL.Text });
  const RichText = IDL.Variant({
    'orderedList' : IDL.Vec(RichTextListItem),
    'code' : RichTextBlock,
    'unorderedList' : IDL.Vec(RichTextListItem),
    'list' : IDL.Vec(RichTextListItem),
    'quote' : RichTextBlock,
    'heading' : HeadingBlock,
    'image' : ImageBlock,
    'paragraph' : RichTextBlock,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Tag = IDL.Text;
  const Time = IDL.Int;
  const Essay = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishDate' : Time,
    'body' : IDL.Vec(RichText),
    'tags' : IDL.Vec(Tag),
    'heroImage' : IDL.Opt(ExternalBlob),
    'subtitle' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PageId = IDL.Text;
  const PageContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Vec(RichText),
    'links' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'subtitle' : IDL.Text,
  });
  const WritingPageContent = IDL.Record({
    'title' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEssay' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(RichText),
          IDL.Opt(ExternalBlob),
          IDL.Vec(Tag),
          Time,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEssay' : IDL.Func([IDL.Nat], [], []),
    'filterPublishedEssaysByTag' : IDL.Func([Tag], [IDL.Vec(Essay)], ['query']),
    'getAllEssaysForAdmin' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEssayForAdmin' : IDL.Func([IDL.Nat], [Essay], ['query']),
    'getPageContent' : IDL.Func([PageId], [PageContent], ['query']),
    'getPublishedEssay' : IDL.Func([IDL.Nat], [Essay], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWritingPageContent' : IDL.Func([], [WritingPageContent], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeDefaultPages' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPublishedEssays' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEssay' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(RichText),
          IDL.Opt(ExternalBlob),
          IDL.Vec(Tag),
          Time,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updatePageContent' : IDL.Func([PageId, PageContent], [], []),
    'updateWritingPageContent' : IDL.Func([WritingPageContent], [], []),
    'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };